# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "CV"
  url = "#cv"
  weight = 10

[[main]]
  name = "Posts"
  url = "#posts"
  weight = 20
  
[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30
  
[[main]]
  name = "Motivation"
  url = "motivation/"
  weight = 40

[[main]]
  name = "Research Interests"
  url = "research-interests/"
  weight = 50

[[main]]
  name = "Teaching"
  url = "teaching/"
  weight = 60

[[main]]
  name = "Diversity"
  url = "diversity/"
  weight = 70



[[main]]
  name = "About Me"
  url = "about-me/"
  weight = 80
  
[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
